"""
Build ReEntryAI_run2.ipynb -- a clean, well-organized end-to-end notebook
for the Orion CM entry simulation with interval supervisor and RCS analysis.

Outputs every bit of trajectory/interval/sim data into revision_v1/ and
produces a rich set of diagnostic plots. Run this script to (re)generate
the notebook.
"""

import json
import os

NB_PATH = os.path.join(os.path.dirname(__file__), "ReEntryAI_run2.ipynb")


def md(*lines):
    return {"cell_type": "markdown", "metadata": {}, "source": _src(lines)}


def code(*lines):
    return {
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": _src(lines),
    }


def _src(lines):
    text = "\n".join(lines)
    out = text.split("\n")
    return [ln + "\n" for ln in out[:-1]] + ([out[-1]] if out[-1] else [])


cells = []

# ---------------------------------------------------------------------------
# Title and overview
# ---------------------------------------------------------------------------
cells.append(md(
    "# ReEntryAI Run v2 -- Orion CM Entry with Interval Supervisor and RCS",
    "",
    "End-to-end simulation notebook. Drives the corrected 3DOF translational dynamics",
    "with the Orion CM trim aero database, a heat-aware predictor-corrector guidance",
    "law, a physical bank actuator, a PD roll torque controller, and a 12-thruster RCS.",
    "Interval propagation runs alongside the nominal trajectory to provide uncertainty",
    "tubes for every state.",
    "",
    "**All outputs are written to `revision_v1/` inside `StochasticEntrySim/`.**",
    "",
    "## Sections",
    "0. Setup (imports, helpers, output folder)",
    "1. Configuration (vehicle, guidance, control stack, RCS, supervisor)",
    "2. Initial state",
    "3. Main simulation loop",
    "4. Save raw data",
    "5. Trajectory diagnostics (ground track, 3D descent tube)",
    "6. State time histories with interval bands (altitude, speed, gamma, chi)",
    "7. Interval supervisor diagnostics (widths, density, dynamic pressure)",
    "8. Heating envelope (qdot, Q, heat shield map)",
    "9. Guidance candidate analysis",
    "10. RCS firing analysis",
    "11. Final summary",
))

# ---------------------------------------------------------------------------
# 0. Setup
# ---------------------------------------------------------------------------
cells.append(md("## 0. Setup"))

cells.append(code(
    "# Imports",
    "import json",
    "import math",
    "import os",
    "from pathlib import Path",
    "from typing import List",
    "",
    "import numpy as np",
    "import pandas as pd",
    "import matplotlib.pyplot as plt",
    "from matplotlib.patches import Patch",
    "from mpl_toolkits.mplot3d import Axes3D  # noqa: F401  (registers 3d projection)",
    "",
    "import constants",
    "import AtmosphereModel",
    "import control",
    "import ReactionControl",
    "",
    "from interval_math import Interval, promote",
    "from math_3d import (",
    "    IntervalSupervisorConfig,",
    "    annotate_nominal_state_with_interval_supervisor,",
    "    f_interval,",
    "    nominal_state_to_interval_box,",
    "    nominal_aero_forces_from_state,",
    "    nominal_eom_step,",
    "    nominal_heating_envelope_from_state,",
    ")",
    "from control import (",
    "    ReentryState,",
    "    GuidanceScheduler,",
    "    SimpleBankGuidance,",
    "    BasicObservationProvider,",
    "    BankActuatorLimits,",
    "    BankActuator,",
    "    RollTorqueController,",
    "    CapsuleControlConfig,",
    "    CapsuleControlStack,",
    "    wrap_to_pi,",
    ")",
    "from ReactionControl import build_orion_cm_rcs_12",
    "from point_math_3d import make_initial_capsule_attitude, step_closed_loop_milestone1, aero_forces",
    "",
    "plt.rcParams['figure.dpi'] = 110",
    "plt.rcParams['axes.grid'] = True",
    "pd.set_option('display.max_columns', 200)",
    "pd.set_option('display.width', 240)",
))

cells.append(code(
    "# Output folder -- everything goes in revision_v1/",
    "OUTPUT_DIR = Path(__file__).parent / 'revision_v1' if '__file__' in globals() else Path.cwd() / 'revision_v1'",
    "OUTPUT_DIR.mkdir(parents=True, exist_ok=True)",
    "FIG_DIR = OUTPUT_DIR / 'figures'",
    "FIG_DIR.mkdir(parents=True, exist_ok=True)",
    "print('Output dir :', OUTPUT_DIR)",
    "print('Figure dir :', FIG_DIR)",
    "",
    "def save_fig(name):",
    "    \"\"\"Save the current figure into the figures folder under revision_v1/.\"\"\"",
    "    path = FIG_DIR / f'{name}.png'",
    "    plt.savefig(path, bbox_inches='tight')",
    "    print(f'  saved {path.relative_to(OUTPUT_DIR.parent)}')",
))

cells.append(code(
    "# Helper functions",
    "STATE_NAMES = ['r_m', 'phi_rad', 'lam_rad', 'V_mps', 'gamma_rad', 'chi_rad']",
    "",
    "def deg(x_rad):",
    "    return math.degrees(x_rad)",
    "",
    "def alt_from_r(r_m):",
    "    return r_m - constants.RADIUS_EARTH",
    "",
    "def wrap_angle_rad(x_rad):",
    "    return wrap_to_pi(float(x_rad))",
    "",
    "def atmosphere_from_state_vector(x):",
    "    r_m, _, _, V_mps, _, _ = x",
    "    alt_m = max(0.0, alt_from_r(r_m))",
    "    atm = AtmosphereModel.US_Standard_ATM(alt_m)",
    "    rho = atm['rho_kgm3'] if atm['rho_kgm3'] is not None else 0.0",
    "    T_K = atm['T_K'] if atm['T_K'] is not None else np.nan",
    "    p_Pa = atm['p_Pa'] if atm['p_Pa'] is not None else np.nan",
    "    q_pa = 0.5 * rho * V_mps * V_mps",
    "    return {'alt_m': alt_m, 'rho_kgm3': rho, 'T_K': T_K, 'p_Pa': p_Pa, 'q_pa': q_pa}",
))

# ---------------------------------------------------------------------------
# 1. Configuration
# ---------------------------------------------------------------------------
cells.append(md("## 1. Configuration"))

cells.append(code(
    "# Vehicle parameters -- use the Orion CM trim aero database we added in math_3d.py",
    "params = {",
    "    'mass_kg': float(constants.CAPSULE_MASS_KG),",
    "    'ref_area_m2': float(constants.CAPSULE_REFERENCE_AREA_M2),",
    "    'aero_model': 'orion_cm_trim',",
    "    'CD_const': 1.15,   # fallback only",
    "    'CL_const': 0.28,",
    "}",
    "",
    "dt_s = float(constants.ENTRY_DT_S)",
    "t_final_s = 1000.0",
    "num_steps = int(t_final_s / dt_s)",
    "Izz_kgm2 = float(constants.CAPSULE_IZZ_KGM2)",
    "",
    "# Landing target",
    "target_phi_rad = math.radians(15.00)",
    "target_lam_rad = math.radians(15.00)",
    "",
    "trajectory_id = 'revision_v1_traj_000'",
    "print('dt_s =', dt_s, ' num_steps =', num_steps, ' t_final_s =', t_final_s)",
))

cells.append(code(
    "# Guidance + control stack",
    "control_cfg = CapsuleControlConfig(guidance_period_s=float(constants.GUIDANCE_PERIOD_S))",
    "guidance_scheduler = GuidanceScheduler(period_s=float(constants.GUIDANCE_PERIOD_S))",
    "",
    "guidance_law = SimpleBankGuidance(",
    "    target_phi_rad=target_phi_rad,",
    "    target_lam_rad=target_lam_rad,",
    "    params=dict(params),",
    "    max_bank_deg=70.0,",
    "    min_bank_deg=40.0,",
    "    velocity_enable_mps=40_000.0,",
    "    predictor_horizon_steps=int(constants.PREDICTOR_CORRECTOR_HORIZON_STEPS),",
    "    prediction_dt_s=float(constants.ENTRY_DT_S),",
    "    candidate_bank_deg=[float(v) for v in constants.PREDICTOR_CANDIDATE_BANK_DEG],",
    "    weight_range=float(constants.PREDICTOR_COST_WEIGHT_RANGE),",
    "    weight_heading=float(constants.PREDICTOR_COST_WEIGHT_HEADING),",
    "    weight_cross_track=float(constants.PREDICTOR_COST_WEIGHT_CROSS_TRACK),",
    "    weight_heat=float(constants.PREDICTOR_COST_WEIGHT_HEAT),",
    "    heat_rate_limit=float(constants.HEAT_RATE_LIMIT_DEFAULT),",
    "    heat_load_limit=float(constants.HEAT_LOAD_LIMIT_DEFAULT),",
    "    infeasible_penalty=float(constants.PREDICTOR_HEAT_INFEASIBLE_PENALTY),",
    "    invalid_interval_penalty=float(constants.PREDICTOR_INVALID_INTERVAL_PENALTY),",
    "    include_zero_bank_candidate=True,",
    ")",
    "",
    "observation_provider = BasicObservationProvider(",
    "    target_phi_rad=target_phi_rad,",
    "    target_lam_rad=target_lam_rad,",
    "    params=params,",
    ")",
    "",
    "bank_actuator = BankActuator(BankActuatorLimits(",
    "    sigma_rate_max_rps=math.radians(20.0),",
    "    sigma_accel_max_rps2=math.radians(40.0),",
    "))",
    "",
    "roll_controller = RollTorqueController(",
    "    kp_Nm_per_rad=float(constants.ROLL_KP_NM_PER_RAD),",
    "    kd_Nm_per_rad_s=float(constants.ROLL_KD_NM_PER_RAD_S),",
    "    max_torque_Nm=float(constants.ROLL_CMD_MAX_TORQUE_NM),",
    "    sigma_deadband_rad=float(constants.ROLL_SIGMA_DEADBAND_RAD),",
    "    rate_deadband_rad_s=float(constants.ROLL_RATE_DEADBAND_RAD_S),",
    ")",
    "",
    "capsule_control = CapsuleControlStack(",
    "    cfg=control_cfg,",
    "    scheduler=guidance_scheduler,",
    "    guidance=guidance_law,",
    "    obs_provider=observation_provider,",
    "    bank_actuator=bank_actuator,",
    "    roll_controller=roll_controller,",
    ")",
    "",
    "rcs_system = build_orion_cm_rcs_12()",
    "capsule_control.reset()",
    "rcs_system.reset()",
    "print('Control stack ready. Roll thrusters +z:', rcs_system.roll_pos_names, '  -z:', rcs_system.roll_neg_names)",
))

cells.append(code(
    "# Interval supervisor -- defines the uncertainty tube and recenter/split policies",
    "supervisor_cfg = IntervalSupervisorConfig(",
    "    r_half_width_m=10.0,",
    "    phi_half_width_rad=math.radians(0.01),",
    "    lam_half_width_rad=math.radians(0.01),",
    "    V_half_width_mps=20.0,",
    "    gamma_half_width_rad=math.radians(0.15),",
    "    chi_half_width_rad=math.radians(0.20),",
    "    min_altitude_m=0.0,",
    "    max_altitude_m=130_000.0,",
    "    max_speed_mps=80_000.0,",
    "    max_dynamic_pressure_pa=5.0e7,",
    "    include_heating=True,",
    "    heat_rate_limit=float(constants.HEAT_RATE_LIMIT_DEFAULT),",
    "    heat_load_limit=float(constants.HEAT_LOAD_LIMIT_DEFAULT),",
    "    interval_recenter_enabled=bool(constants.INTERVAL_RECENTER_ENABLED),",
    "    interval_recenter_use_cadence=False,",
    "    interval_recenter_cadence_s=float(constants.INTERVAL_RECENTER_CADENCE_S),",
    "    interval_recenter_width_thresholds=dict(constants.INTERVAL_RECENTER_WIDTH_THRESHOLDS),",
    "    interval_box_split_enabled=bool(constants.INTERVAL_BOX_SPLIT_ENABLED),",
    "    interval_box_split_max_depth=int(constants.INTERVAL_BOX_SPLIT_MAX_DEPTH),",
    "    interval_box_split_width_thresholds=dict(constants.INTERVAL_BOX_SPLIT_WIDTH_THRESHOLDS),",
    "    interval_denominator_safety_V_mps=float(constants.INTERVAL_DENOMINATOR_SAFETY_V_MPS),",
    "    interval_denominator_safety_cos_gamma=float(constants.INTERVAL_DENOMINATOR_SAFETY_COS_GAMMA),",
    "    interval_denominator_safety_cos_phi=float(constants.INTERVAL_DENOMINATOR_SAFETY_COS_PHI),",
    ")",
    "print('Interval supervisor ready. Recenter enabled =', supervisor_cfg.interval_recenter_enabled,",
    "      ' Splitting enabled =', supervisor_cfg.interval_box_split_enabled)",
))

# ---------------------------------------------------------------------------
# 2. Initial state
# ---------------------------------------------------------------------------
cells.append(md("## 2. Initial state"))

cells.append(code(
    "# Entry interface conditions",
    "x_nominal = [",
    "    constants.RADIUS_EARTH + 115_000.0,  # r_m",
    "    math.radians(0.0),                   # phi (latitude)",
    "    math.radians(0.0),                   # lambda (longitude)",
    "    10_500.0,                            # V_mps",
    "    math.radians(-5.5),                  # gamma (flight path angle)",
    "    math.radians(90.0),                  # chi (heading, east-referenced)",
    "]",
    "sigma_actual_0_rad = 0.0",
    "roll_rate_0_rad_s = 0.0",
    "",
    "state_ctrl = ReentryState(",
    "    r_m=float(x_nominal[0]),",
    "    phi_rad=float(x_nominal[1]),",
    "    lam_rad=float(x_nominal[2]),",
    "    V_mps=float(x_nominal[3]),",
    "    gamma_rad=float(x_nominal[4]),",
    "    chi_rad=float(x_nominal[5]),",
    "    sigma_actual_rad=sigma_actual_0_rad,",
    "    roll_rate_rad_s=roll_rate_0_rad_s,",
    ")",
    "capsule_control.reset()",
    "rcs_system.reset()",
    "print(f'Initial: alt = {alt_from_r(x_nominal[0])/1000:.1f} km, V = {x_nominal[3]:.0f} m/s, gamma = {deg(x_nominal[4]):.2f} deg')",
    "print(f'Target : phi = {deg(target_phi_rad):.2f} deg, lam = {deg(target_lam_rad):.2f} deg')",
))

# ---------------------------------------------------------------------------
# 3. Main loop
# ---------------------------------------------------------------------------
cells.append(md(
    "## 3. Main simulation loop",
    "",
    "Each step: control stack -> RCS -> roll attitude -> translational EOM -> interval annotation -> log."
))

cells.append(code(
    "# Controller bridge -- same shape used in the original notebook",
    "def control_step_fn_main(t_s, x_state, sigma_actual_rad, roll_rate_rad_s):",
    "    r_m, phi_rad, lam_rad, V_mps, gamma_rad, chi_rad = [float(v) for v in x_state]",
    "    state_now = ReentryState(",
    "        r_m=r_m, phi_rad=phi_rad, lam_rad=lam_rad, V_mps=V_mps,",
    "        gamma_rad=gamma_rad, chi_rad=chi_rad,",
    "        sigma_actual_rad=float(sigma_actual_rad),",
    "        roll_rate_rad_s=float(roll_rate_rad_s),",
    "    )",
    "    Dr, Dt, Dp, Lr, Lt, Lp, _, _ = aero_forces(",
    "        r=r_m, V=V_mps, gamma=gamma_rad, chi=chi_rad,",
    "        params=params, sigma_actual_rad=float(sigma_actual_rad),",
    "    )",
    "    drag = math.sqrt(Dr*Dr + Dt*Dt + Dp*Dp)",
    "    lift = math.sqrt(Lr*Lr + Lt*Lt + Lp*Lp)",
    "    return capsule_control.step(",
    "        t_s=float(t_s), dt_s=float(dt_s), state=state_now,",
    "        lift_N=lift, drag_N=drag, mass_kg=float(params['mass_kg']),",
    "    )",
))

cells.append(code(
    "# Main loop -- preserves the interval supervisor logic from the original notebook.",
    "x_nom = list(x_nominal)",
    "x_interval = None",
    "interval_heat_shield = None",
    "nominal_heat_shield = None",
    "interval_active = True",
    "interval_failed = False",
    "interval_failure_time_s = np.nan",
    "interval_failure_reason = ''",
    "interval_failure_kind = ''",
    "last_valid_interval_state = None",
    "last_valid_interval_time_s = np.nan",
    "nominal_heat_violation = False",
    "sim_terminated_by_nominal_heat = False",
    "termination_reason = ''",
    "att_nom = make_initial_capsule_attitude(state_ctrl.sigma_actual_rad)",
    "",
    "rows = []",
    "failed_heat_rows = []",
    "thruster_fire_events = []  # one row per (step, thruster_name) fire",
    "",
    "for k in range(num_steps):",
    "    t_s = k * dt_s",
    "    sigma_actual_rad = float(att_nom.sigma_rel_rad)",
    "    roll_rate_rad_s = float(att_nom.omega_b_rad_s[2])",
    "",
    "    if abs(math.cos(x_nom[4])) < 0.2:",
    "        termination_reason = 'nominal_cos_gamma_too_small'",
    "        print(f'Stopping at t = {t_s:.2f} s: cos(gamma) too small')",
    "        break",
    "    if x_nom[3] <= 1.0:",
    "        termination_reason = 'nominal_speed_too_low'",
    "        print(f'Stopping at t = {t_s:.2f} s: speed too low')",
    "        break",
    "    if alt_from_r(x_nom[0]) <= 0.0:",
    "        termination_reason = 'nominal_ground_reached'",
    "        print(f'Stopping at t = {t_s:.2f} s: ground reached')",
    "        break",
    "",
    "    guidance_law.set_prediction_context(",
    "        x_interval_old=x_interval if interval_active else None,",
    "        heat_shield=interval_heat_shield if interval_active else None,",
    "        supervisor_cfg=supervisor_cfg,",
    "        trajectory_id=trajectory_id,",
    "        guidance_cycle_index=k,",
    "        interval_active=bool(interval_active),",
    "    )",
    "",
    "    step_result = step_closed_loop_milestone1(",
    "        t_s=float(t_s), x_trans=list(x_nom), att=att_nom,",
    "        params=params, control_step_fn=control_step_fn_main,",
    "        rcs=rcs_system, dt_s=float(dt_s), Izz_kgm2=float(Izz_kgm2),",
    "    )",
    "    ctrl_out = step_result.control_out",
    "    roll_step = step_result.roll_step",
    "    x_nom_next = list(step_result.x_new)",
    "    dx_nom = list(step_result.dx_trans)",
    "    sigma_actual_next_rad = float(step_result.sigma_actual_after_rad)",
    "    roll_rate_next_rad_s = float(step_result.att_new.omega_b_rad_s[2])",
    "    roll_accel = (roll_rate_next_rad_s - roll_rate_rad_s) / float(dt_s)",
    "",
    "    g_debug = dict(ctrl_out.guidance_debug)",
    "    candidate_dicts = g_debug.get('candidate_dicts', [])",
    "    selected_idx = int(g_debug.get('selected_candidate_index', -1))",
    "",
    "    nominal_aero = nominal_aero_forces_from_state(x=x_nom, sigma_rad=sigma_actual_next_rad, params=params)",
    "    gravity = float(constants.gravity(float(x_nom[0])))",
    "",
    "    heat_info = nominal_heating_envelope_from_state(x_nominal=list(x_nom), dt_s=float(dt_s), heat_shield=nominal_heat_shield)",
    "    nominal_heat_shield = heat_info['heat_shield']",
    "    nominal_heat_qdot = heat_info['qdot_max']",
    "    nominal_heat_Q = heat_info['Q_max']",
    "    nominal_heat_violation = False",
    "    nominal_heat_violation_reason = ''",
    "    if nominal_heat_qdot.hi > float(supervisor_cfg.heat_rate_limit):",
    "        nominal_heat_violation = True; nominal_heat_violation_reason = 'nominal_heat_rate_limit'",
    "    if nominal_heat_Q.hi > float(supervisor_cfg.heat_load_limit):",
    "        nominal_heat_violation = True",
    "        nominal_heat_violation_reason += (',' if nominal_heat_violation_reason else '') + 'nominal_heat_load_limit'",
    "",
    "    annotation = None",
    "    interval_step_recentered = False; interval_step_recenter_reason = ''",
    "    interval_step_split = False; interval_step_split_reason = ''; interval_step_split_depth = 0",
    "    if interval_active:",
    "        annotation = annotate_nominal_state_with_interval_supervisor(",
    "            x_nominal_old=x_nom, params=params,",
    "            sigma_actual_after_rad=sigma_actual_next_rad,",
    "            x_interval_old=x_interval, supervisor_cfg=supervisor_cfg,",
    "            dt_s=dt_s, heat_shield=interval_heat_shield, t_s=t_s,",
    "        )",
    "        interval_step_recentered = bool(annotation.recentered_this_step)",
    "        interval_step_recenter_reason = str(getattr(annotation, 'recenter_reason', ''))",
    "        interval_step_split = bool(annotation.split_this_step)",
    "        interval_step_split_reason = str(getattr(annotation, 'split_reason', ''))",
    "        interval_step_split_depth = int(annotation.split_depth_used)",
    "        if annotation.last_valid_interval_state is not None:",
    "            last_valid_interval_state = [Interval(iv.lo, iv.hi) for iv in annotation.last_valid_interval_state]",
    "            last_valid_interval_time_s = float(t_s)",
    "        if annotation.interval_valid and not annotation.interval_heat_violation:",
    "            x_interval = [Interval(iv.lo, iv.hi) for iv in annotation.x_interval_new]",
    "            interval_heat_shield = getattr(annotation, 'heat_shield', interval_heat_shield)",
    "        else:",
    "            interval_failed = True; interval_active = False",
    "            interval_failure_time_s = float(t_s + dt_s)",
    "            interval_failure_reason = str(annotation.interval_failure_reason)",
    "            interval_failure_kind = str(annotation.interval_failure_kind)",
    "            interval_heat_shield = None; x_interval = None",
    "",
    "    atm = atmosphere_from_state_vector(x_nom)",
    "    active_names = roll_step.fire_cmd.active_names()",
    "    obs = ctrl_out.obs",
    "",
    "    # Record one row per thruster that fired this step (for raster plot)",
    "    for tn in active_names:",
    "        thruster_fire_events.append({'step': k, 't_s': t_s, 'thruster': tn})",
    "",
    "    row = {",
    "        'step': k, 't_s': t_s,",
    "        'guidance_updated': int(bool(ctrl_out.guidance_updated)),",
    "        'trajectory_id': trajectory_id,",
    "        'guidance_cycle_index': int(g_debug.get('guidance_cycle_index', k)),",
    "        # bank / roll",
    "        'sigma_cmd_rad': float(ctrl_out.sigma_cmd_rad),",
    "        'sigma_target_rad': float(ctrl_out.sigma_target_rad),",
    "        'sigma_actual_rad': sigma_actual_next_rad,",
    "        'roll_rate_rad_s': roll_rate_next_rad_s,",
    "        'roll_accel_rad_s2': roll_accel,",
    "        # RCS",
    "        'tau_roll_cmd_Nm': float(ctrl_out.tau_roll_cmd_Nm),",
    "        'tau_roll_capacity_Nm': float(roll_step.tau_roll_capacity_Nm),",
    "        'tau_roll_realized_Nm': float(roll_step.wrench.torque_b_Nm[2]),",
    "        'requested_duty': float(roll_step.requested_duty),",
    "        'fired_this_step': int(bool(roll_step.fired_this_step)),",
    "        'num_internal_steps': int(roll_step.num_internal_steps),",
    "        'num_fired_internal_steps': int(roll_step.num_fired_internal_steps),",
    "        'roll_pos_is_on': int(bool(roll_step.roll_pos_is_on)),",
    "        'roll_neg_is_on': int(bool(roll_step.roll_neg_is_on)),",
    "        'roll_pos_backlog_s': float(roll_step.roll_pos_backlog_s),",
    "        'roll_neg_backlog_s': float(roll_step.roll_neg_backlog_s),",
    "        'active_thrusters': ','.join(active_names),",
    "        'num_active_thrusters': len(active_names),",
    "        'force_x_from_rcs_N': float(roll_step.wrench.force_b_N[0]),",
    "        'force_y_from_rcs_N': float(roll_step.wrench.force_b_N[1]),",
    "        'force_z_from_rcs_N': float(roll_step.wrench.force_b_N[2]),",
    "        # translational state",
    "        'r_m': float(x_nom[0]), 'phi_rad': float(x_nom[1]), 'lam_rad': float(x_nom[2]),",
    "        'V_mps': float(x_nom[3]), 'gamma_rad': float(x_nom[4]), 'chi_rad': float(x_nom[5]),",
    "        'alt_m': float(atm['alt_m']),",
    "        'rho_kgm3': float(atm['rho_kgm3']),",
    "        'q_pa': float(atm['q_pa']),",
    "        'T_K': float(atm['T_K']) if not pd.isna(atm['T_K']) else np.nan,",
    "        'p_Pa': float(atm['p_Pa']) if not pd.isna(atm['p_Pa']) else np.nan,",
    "        # aero",
    "        'drag_mag_N': float(nominal_aero['drag_mag_N']),",
    "        'lift_mag_N': float(nominal_aero['lift_mag_N']),",
    "        'CD': float(nominal_aero['CD']),",
    "        'CL': float(nominal_aero['CL']),",
    "        'LD': float(nominal_aero['LD']),",
    "        'gravity_mps2': gravity,",
    "        # geometry",
    "        'range_to_go_m': float(obs.get('range_to_go_m', np.nan)),",
    "        'heading_error_rad': float(obs.get('heading_error_rad', np.nan)),",
    "        'cross_track_error_m': float(obs.get('cross_track_error_m', np.nan)),",
    "        'along_track_error_m': float(obs.get('along_track_error_m', np.nan)),",
    "        # interval status",
    "        'interval_active': int(interval_active),",
    "        'interval_failed': int(interval_failed),",
    "        'interval_failure_time_s': float(interval_failure_time_s) if np.isfinite(interval_failure_time_s) else np.nan,",
    "        'interval_failure_reason': str(interval_failure_reason),",
    "        'interval_failure_kind': str(interval_failure_kind),",
    "        'interval_step_recentered': int(interval_step_recentered),",
    "        'interval_step_recenter_reason': interval_step_recenter_reason,",
    "        'interval_step_split': int(interval_step_split),",
    "        'interval_step_split_reason': interval_step_split_reason,",
    "        'interval_step_split_depth': interval_step_split_depth,",
    "        # nominal heat",
    "        'nominal_heat_qdot_max_hi': float(nominal_heat_qdot.hi),",
    "        'nominal_heat_Q_max_hi': float(nominal_heat_Q.hi),",
    "        'nominal_heat_violation': int(nominal_heat_violation),",
    "        # guidance",
    "        'guidance_selected_candidate_index': int(selected_idx),",
    "        'guidance_chosen_sigma_cmd_deg': float(g_debug.get('chosen_sigma_cmd_deg', np.nan)),",
    "        'guidance_chosen_sigma_mag_deg': float(g_debug.get('chosen_sigma_mag_deg', np.nan)),",
    "        'guidance_selected_total_cost': float(g_debug.get('selected_total_cost', np.nan)),",
    "        'guidance_selected_geometry_cost': float(g_debug.get('selected_geometry_cost', np.nan)),",
    "        'guidance_selected_heat_penalty': float(g_debug.get('selected_heat_penalty', np.nan)),",
    "        'guidance_any_feasible': int(bool(g_debug.get('any_feasible_candidate', True))),",
    "        'guidance_candidate_sigma_deg_json': json.dumps([float(c.get('sigma_cmd_deg', np.nan)) for c in candidate_dicts]),",
    "        'guidance_candidate_cost_json': json.dumps([float(c.get('total_cost', np.nan)) for c in candidate_dicts]),",
    "        'guidance_candidate_heat_flag_json': json.dumps([int(bool(c.get('fully_feasible', False))) for c in candidate_dicts]),",
    "    }",
    "",
    "    # Interval bands (NaN when interval has failed)",
    "    if annotation is not None:",
    "        row['interval_alt_lo'] = float(annotation.altitude_interval.lo)",
    "        row['interval_alt_hi'] = float(annotation.altitude_interval.hi)",
    "        row['interval_rho_lo'] = float(annotation.rho_interval.lo)",
    "        row['interval_rho_hi'] = float(annotation.rho_interval.hi)",
    "        row['interval_q_lo'] = float(annotation.q_interval.lo)",
    "        row['interval_q_hi'] = float(annotation.q_interval.hi)",
    "        state_base_names = ['r', 'phi', 'lam', 'V', 'gamma', 'chi']",
    "        for i, base in enumerate(state_base_names):",
    "            row[f'{base}_lo'] = float(annotation.x_interval_new[i].lo)",
    "            row[f'{base}_hi'] = float(annotation.x_interval_new[i].hi)",
    "            row[f'{base}_width'] = float(annotation.x_interval_new[i].width())",
    "        row['width_r_m'] = float(annotation.state_widths_new['r'])",
    "        row['width_V_mps'] = float(annotation.state_widths_new['V'])",
    "        row['width_gamma_rad'] = float(annotation.state_widths_new['gamma'])",
    "        row['width_chi_rad'] = float(annotation.state_widths_new['chi'])",
    "        row['dx_width_V'] = float(annotation.dx_widths['V'])",
    "        row['dx_width_gamma'] = float(annotation.dx_widths['gamma'])",
    "        row['dx_width_chi'] = float(annotation.dx_widths['chi'])",
    "        row['heating_qdot_max_hi'] = float(annotation.heating_qdot_max_interval.hi) if annotation.heating_qdot_max_interval else np.nan",
    "        row['heating_Q_max_hi'] = float(annotation.heating_Q_max_interval.hi) if annotation.heating_Q_max_interval else np.nan",
    "        row['safety_status'] = str(annotation.safety_status)",
    "    else:",
    "        for key in ['interval_alt_lo','interval_alt_hi','interval_rho_lo','interval_rho_hi','interval_q_lo','interval_q_hi',",
    "                    'width_r_m','width_V_mps','width_gamma_rad','width_chi_rad',",
    "                    'dx_width_V','dx_width_gamma','dx_width_chi',",
    "                    'heating_qdot_max_hi','heating_Q_max_hi']:",
    "            row[key] = np.nan",
    "        for base in ['r', 'phi', 'lam', 'V', 'gamma', 'chi']:",
    "            row[f'{base}_lo'] = np.nan; row[f'{base}_hi'] = np.nan; row[f'{base}_width'] = np.nan",
    "        row['safety_status'] = 'interval_inactive'",
    "",
    "    rows.append(row)",
    "",
    "    # Track guidance cycles that selected an infeasible heat candidate",
    "    if bool(ctrl_out.guidance_updated):",
    "        sel_heat_feasible = bool(g_debug.get('selected_candidate_heat_feasible', True))",
    "        if not sel_heat_feasible:",
    "            failed_heat_rows.append({",
    "                'step': k, 't_s': t_s,",
    "                'V_mps': x_nom[3], 'alt_m': atm['alt_m'],",
    "                'chosen_sigma_deg': float(g_debug.get('chosen_sigma_cmd_deg', np.nan)),",
    "                'failure_reason': str(g_debug.get('selected_failure_reason', '')),",
    "            })",
    "",
    "    x_nom = list(x_nom_next)",
    "    att_nom = step_result.att_new",
    "",
    "    if nominal_heat_violation:",
    "        sim_terminated_by_nominal_heat = True",
    "        termination_reason = nominal_heat_violation_reason",
    "        print(f'Stopping at t = {t_s+dt_s:.2f} s: nominal heat violation ({nominal_heat_violation_reason})')",
    "        break",
    "",
    "print(f'Loop done. Steps simulated: {len(rows)}.  termination_reason = {termination_reason!r}')",
))

# ---------------------------------------------------------------------------
# 4. Save data
# ---------------------------------------------------------------------------
cells.append(md("## 4. Save raw data into `revision_v1/`"))

cells.append(code(
    "df = pd.DataFrame(rows)",
    "failed_heat_df = pd.DataFrame(failed_heat_rows)",
    "thruster_fires_df = pd.DataFrame(thruster_fire_events)",
    "print(f'Trajectory rows: {len(df)}   columns: {len(df.columns)}')",
    "print(f'Failed heat rows: {len(failed_heat_df)}')",
    "print(f'Thruster fire events: {len(thruster_fires_df)}')",
    "df.head()",
))

cells.append(code(
    "# Persist everything",
    "traj_csv = OUTPUT_DIR / 'trajectory.csv'",
    "fires_csv = OUTPUT_DIR / 'thruster_fires.csv'",
    "heat_fail_csv = OUTPUT_DIR / 'failed_heat_cycles.csv'",
    "summary_json = OUTPUT_DIR / 'run_summary.json'",
    "",
    "df.to_csv(traj_csv, index=False)",
    "thruster_fires_df.to_csv(fires_csv, index=False)",
    "failed_heat_df.to_csv(heat_fail_csv, index=False)",
    "",
    "summary = {",
    "    'trajectory_id': trajectory_id,",
    "    'num_logged_steps': int(len(df)),",
    "    'termination_reason': termination_reason,",
    "    'sim_terminated_by_nominal_heat': bool(sim_terminated_by_nominal_heat),",
    "    'interval_failed_detected': bool(df['interval_failed'].max() > 0) if len(df) else False,",
    "    'interval_recenter_count': int(df['interval_step_recentered'].sum()) if len(df) else 0,",
    "    'interval_split_count': int(df['interval_step_split'].sum()) if len(df) else 0,",
    "    'guidance_updates': int(df['guidance_updated'].sum()) if len(df) else 0,",
    "    'thruster_fire_events': int(len(thruster_fires_df)),",
    "    'final_t_s': float(df['t_s'].iloc[-1]) if len(df) else 0.0,",
    "    'final_alt_m': float(df['alt_m'].iloc[-1]) if len(df) else 0.0,",
    "    'final_V_mps': float(df['V_mps'].iloc[-1]) if len(df) else 0.0,",
    "    'final_gamma_deg': float(math.degrees(df['gamma_rad'].iloc[-1])) if len(df) else 0.0,",
    "    'aero_model': params['aero_model'],",
    "    'target_phi_deg': math.degrees(target_phi_rad),",
    "    'target_lam_deg': math.degrees(target_lam_rad),",
    "    'output_files': {",
    "        'trajectory_csv': str(traj_csv),",
    "        'thruster_fires_csv': str(fires_csv),",
    "        'failed_heat_csv': str(heat_fail_csv),",
    "    },",
    "}",
    "with open(summary_json, 'w') as f:",
    "    json.dump(summary, f, indent=2)",
    "",
    "print('Saved:')",
    "print(f'  {traj_csv}')",
    "print(f'  {fires_csv}')",
    "print(f'  {heat_fail_csv}')",
    "print(f'  {summary_json}')",
    "summary",
))

# ---------------------------------------------------------------------------
# 5. Trajectory diagnostics
# ---------------------------------------------------------------------------
cells.append(md("## 5. Trajectory diagnostics"))

cells.append(code(
    "# Ground track with start, end, and target (like the user's first image)",
    "track = df.copy()",
    "track['phi_deg'] = np.degrees(track['phi_rad'])",
    "track['lam_deg'] = np.degrees(track['lam_rad'])",
    "",
    "fig, ax = plt.subplots(figsize=(10, 7))",
    "ax.plot(track['lam_deg'], track['phi_deg'], lw=2, label='Nominal ground track', color='C0')",
    "ax.scatter(track['lam_deg'].iloc[0], track['phi_deg'].iloc[0], s=120, marker='o', color='C0', label='Start')",
    "ax.scatter(track['lam_deg'].iloc[-1], track['phi_deg'].iloc[-1], s=140, marker='s', color='C1', label='End')",
    "ax.scatter(math.degrees(target_lam_rad), math.degrees(target_phi_rad),",
    "           s=200, marker='x', color='C2', linewidths=3, label='Target')",
    "ax.set_xlabel('Longitude deg'); ax.set_ylabel('Latitude deg')",
    "ax.set_title('Ground track with start, end, and target')",
    "ax.legend(); ax.set_aspect('equal', 'datalim')",
    "save_fig('05a_ground_track')",
    "plt.show()",
))

cells.append(code(
    "# Local-tangent-plane conversion -- North, East, Altitude",
    "phi0 = float(track['phi_rad'].iloc[0]); lam0 = float(track['lam_rad'].iloc[0])",
    "R = float(constants.RADIUS_EARTH)",
    "track['north_m'] = R * (track['phi_rad'] - phi0)",
    "track['east_m']  = R * (track['lam_rad'] - lam0) * math.cos(phi0)",
    "",
    "# Build interval-corner curves from interval altitude bounds and the in-plane track",
    "has_interval = track['interval_alt_lo'].notna()",
    "tr_iv = track[has_interval]",
    "",
    "fig = plt.figure(figsize=(16, 6))",
    "ax1 = fig.add_subplot(1, 2, 1, projection='3d')",
    "ax2 = fig.add_subplot(1, 2, 2, projection='3d')",
    "for ax, elev, azim, title in [(ax1, 25, -60, '3D descent tube view 1'),",
    "                              (ax2, 25,  120, '3D descent tube view 2')]:",
    "    ax.plot(track['north_m'], track['east_m'], track['alt_m'], color='C0', lw=2, label='Nominal trajectory')",
    "    if len(tr_iv):",
    "        ax.plot(tr_iv['north_m'], tr_iv['east_m'], tr_iv['interval_alt_lo'],",
    "                color='C1', ls='--', lw=1, label='Interval low corner')",
    "        ax.plot(tr_iv['north_m'], tr_iv['east_m'], tr_iv['interval_alt_hi'],",
    "                color='C2', ls='--', lw=1, label='Interval high corner')",
    "    ax.scatter(track['north_m'].iloc[0], track['east_m'].iloc[0], track['alt_m'].iloc[0],",
    "               s=80, marker='o', color='C0', label='Start')",
    "    ax.scatter(track['north_m'].iloc[-1], track['east_m'].iloc[-1], track['alt_m'].iloc[-1],",
    "               s=80, marker='s', color='C1', label='End')",
    "    ax.set_xlabel('North m'); ax.set_ylabel('East m'); ax.set_zlabel('Altitude m')",
    "    ax.set_title(title); ax.view_init(elev=elev, azim=azim)",
    "    ax.legend(loc='upper left', fontsize=8)",
    "save_fig('05b_3d_descent_tube')",
    "plt.show()",
))

# ---------------------------------------------------------------------------
# 6. State time histories with interval bands
# ---------------------------------------------------------------------------
cells.append(md(
    "## 6. State time histories with interval uncertainty bands",
    "",
    "These reproduce the 'conditional uncertainty propagation' style plots from the original notebook."
))

cells.append(code(
    "# Helper: shade the interval band where it is finite",
    "def plot_with_band(ax, t, nominal, lo, hi, title, ylabel, nom_color='C0', lo_color='C1', hi_color='C2',",
    "                   nom_label='Nominal', lo_label='Interval low', hi_label='Interval high'):",
    "    ax.plot(t, nominal, color=nom_color, lw=2, label=nom_label)",
    "    mask = lo.notna() & hi.notna()",
    "    if mask.any():",
    "        ax.plot(t[mask], lo[mask], color=lo_color, lw=1.2, label=lo_label)",
    "        ax.plot(t[mask], hi[mask], color=hi_color, lw=1.2, label=hi_label)",
    "        ax.fill_between(t[mask], lo[mask], hi[mask], color=nom_color, alpha=0.15)",
    "    ax.set_title(title); ax.set_xlabel('Time s'); ax.set_ylabel(ylabel)",
    "    ax.legend(loc='best')",
))

cells.append(code(
    "# Altitude (km) vs time with interval band",
    "fig, ax = plt.subplots(figsize=(11, 4))",
    "plot_with_band(ax, df['t_s'], df['alt_m']/1000.0,",
    "               df['interval_alt_lo']/1000.0, df['interval_alt_hi']/1000.0,",
    "               'Altitude with interval band', 'Altitude km')",
    "save_fig('06a_altitude')",
    "plt.show()",
))

cells.append(code(
    "# Speed (m/s) vs time with interval band",
    "fig, ax = plt.subplots(figsize=(11, 4))",
    "plot_with_band(ax, df['t_s'], df['V_mps'], df['V_lo'], df['V_hi'],",
    "               'Speed with interval band', 'V m/s')",
    "save_fig('06b_speed')",
    "plt.show()",
))

cells.append(code(
    "# Flight path angle (deg) vs time -- matches the user's image",
    "fig, ax = plt.subplots(figsize=(11, 4))",
    "plot_with_band(ax, df['t_s'],",
    "               np.degrees(df['gamma_rad']),",
    "               np.degrees(df['gamma_lo']),",
    "               np.degrees(df['gamma_hi']),",
    "               'Conditional uncertainty propagation for flight path angle', 'Gamma deg',",
    "               nom_label='Nominal gamma', lo_label='Interval gamma low', hi_label='Interval gamma high')",
    "save_fig('06c_gamma')",
    "plt.show()",
))

cells.append(code(
    "# Heading (deg) vs time -- matches the user's image",
    "fig, ax = plt.subplots(figsize=(11, 4))",
    "plot_with_band(ax, df['t_s'],",
    "               np.degrees(df['chi_rad']),",
    "               np.degrees(df['chi_lo']),",
    "               np.degrees(df['chi_hi']),",
    "               'Conditional uncertainty propagation for heading angle', 'Chi deg',",
    "               nom_label='Nominal chi', lo_label='Interval chi low', hi_label='Interval chi high')",
    "save_fig('06d_chi')",
    "plt.show()",
))

cells.append(code(
    "# Lat / lon with interval band",
    "fig, axes = plt.subplots(1, 2, figsize=(14, 4))",
    "plot_with_band(axes[0], df['t_s'], np.degrees(df['phi_rad']),",
    "               np.degrees(df['phi_lo']), np.degrees(df['phi_hi']),",
    "               'Latitude with interval band', 'phi deg')",
    "plot_with_band(axes[1], df['t_s'], np.degrees(df['lam_rad']),",
    "               np.degrees(df['lam_lo']), np.degrees(df['lam_hi']),",
    "               'Longitude with interval band', 'lambda deg')",
    "save_fig('06e_lat_lon')",
    "plt.show()",
))

# ---------------------------------------------------------------------------
# 7. Interval supervisor diagnostics
# ---------------------------------------------------------------------------
cells.append(md("## 7. Interval supervisor diagnostics"))

cells.append(code(
    "# State component widths over time. Health-intervention steps are marked.",
    "width_cols = [('r_width', 'r_m'), ('V_width', 'V_mps'),",
    "              ('gamma_width', 'gamma_rad'), ('chi_width', 'chi_rad')]",
    "",
    "fig, axes = plt.subplots(2, 2, figsize=(13, 7), sharex=True)",
    "recenter_steps = df[df['interval_step_recentered']==1]['t_s']",
    "split_steps = df[df['interval_step_split']==1]['t_s']",
    "for ax, (col, label) in zip(axes.ravel(), width_cols):",
    "    ax.plot(df['t_s'], df[col], lw=1.5)",
    "    for ts in recenter_steps:",
    "        ax.axvline(ts, color='orange', alpha=0.25, lw=0.7)",
    "    for ts in split_steps:",
    "        ax.axvline(ts, color='red', alpha=0.35, lw=0.7)",
    "    ax.set_title(f'Width of {label}')",
    "    ax.set_xlabel('Time s'); ax.set_ylabel('width')",
    "fig.suptitle('Interval state-component widths (orange = recenter, red = split)')",
    "fig.tight_layout()",
    "save_fig('07a_state_widths')",
    "plt.show()",
))

cells.append(code(
    "# Density and dynamic pressure interval bands",
    "fig, axes = plt.subplots(1, 2, figsize=(14, 4))",
    "plot_with_band(axes[0], df['t_s'], df['rho_kgm3'], df['interval_rho_lo'], df['interval_rho_hi'],",
    "               'Density with interval band', 'rho kg/m^3')",
    "axes[0].set_yscale('log')",
    "plot_with_band(axes[1], df['t_s'], df['q_pa'], df['interval_q_lo'], df['interval_q_hi'],",
    "               'Dynamic pressure with interval band', 'q Pa')",
    "save_fig('07b_density_q')",
    "plt.show()",
))

# ---------------------------------------------------------------------------
# 8. Heating envelope
# ---------------------------------------------------------------------------
cells.append(md("## 8. Heating envelope"))

cells.append(code(
    "# Instantaneous heat rate and accumulated heat load -- nominal and interval upper bound",
    "fig, axes = plt.subplots(1, 2, figsize=(14, 4))",
    "axes[0].plot(df['t_s'], df['nominal_heat_qdot_max_hi']/1e6, color='C0', lw=2, label='Nominal qdot hi')",
    "if df['heating_qdot_max_hi'].notna().any():",
    "    axes[0].plot(df['t_s'], df['heating_qdot_max_hi']/1e6, color='C2', lw=1, ls='--', label='Interval qdot hi')",
    "axes[0].axhline(constants.HEAT_RATE_LIMIT_DEFAULT/1e6, color='red', ls=':', label='heat rate limit')",
    "axes[0].set_xlabel('Time s'); axes[0].set_ylabel('qdot MW/m^2'); axes[0].set_title('Peak heating rate')",
    "axes[0].legend()",
    "",
    "axes[1].plot(df['t_s'], df['nominal_heat_Q_max_hi']/1e6, color='C0', lw=2, label='Nominal Q hi')",
    "if df['heating_Q_max_hi'].notna().any():",
    "    axes[1].plot(df['t_s'], df['heating_Q_max_hi']/1e6, color='C2', lw=1, ls='--', label='Interval Q hi')",
    "axes[1].axhline(constants.HEAT_LOAD_LIMIT_DEFAULT/1e6, color='red', ls=':', label='heat load limit')",
    "axes[1].set_xlabel('Time s'); axes[1].set_ylabel('Q MJ/m^2'); axes[1].set_title('Accumulated heat load')",
    "axes[1].legend()",
    "save_fig('08a_heating_envelope')",
    "plt.show()",
))

cells.append(code(
    "# Heat shield face map -- accumulated heat load per ring/sector at end of trajectory",
    "if nominal_heat_shield is not None:",
    "    shield = nominal_heat_shield",
    "    n_rings = shield.num_rings; n_sectors = shield.num_sectors",
    "    Q_grid = np.zeros((n_rings, n_sectors))",
    "    for ring in range(n_rings):",
    "        for sector in range(n_sectors):",
    "            idx = shield.cell_index(ring, sector)",
    "            iv = shield.Q[idx]",
    "            Q_grid[ring, sector] = 0.5 * (float(iv.lo) + float(iv.hi))",
    "    fig, ax = plt.subplots(figsize=(8, 5))",
    "    im = ax.imshow(Q_grid/1e6, aspect='auto', cmap='hot', origin='lower')",
    "    ax.set_xlabel('Sector index'); ax.set_ylabel('Ring index (0 = inner)')",
    "    ax.set_title('Heat shield accumulated heat load Q (MJ/m^2)')",
    "    plt.colorbar(im, ax=ax, label='Q MJ/m^2')",
    "    save_fig('08b_heat_shield_map')",
    "    plt.show()",
    "else:",
    "    print('No nominal heat shield available')",
))

# ---------------------------------------------------------------------------
# 9. Guidance candidate analysis
# ---------------------------------------------------------------------------
cells.append(md("## 9. Guidance candidate analysis"))

cells.append(code(
    "g = df[df['guidance_updated']==1].copy()",
    "print('Guidance updates:', len(g))",
    "",
    "fig, axes = plt.subplots(2, 1, figsize=(12, 7), sharex=True)",
    "axes[0].plot(g['t_s'], g['guidance_chosen_sigma_cmd_deg'], marker='o', ms=3, lw=1, label='chosen sigma_cmd')",
    "axes[0].plot(df['t_s'], np.degrees(df['sigma_actual_rad']), color='C1', alpha=0.7, label='sigma_actual')",
    "axes[0].set_ylabel('Bank deg'); axes[0].set_title('Commanded vs actual bank')",
    "axes[0].legend()",
    "",
    "axes[1].plot(g['t_s'], g['guidance_selected_total_cost'], color='C3', label='total cost')",
    "axes[1].plot(g['t_s'], g['guidance_selected_geometry_cost'], color='C0', alpha=0.6, label='geometry cost')",
    "axes[1].plot(g['t_s'], g['guidance_selected_heat_penalty'], color='C2', alpha=0.6, label='heat penalty')",
    "axes[1].set_yscale('symlog'); axes[1].set_xlabel('Time s'); axes[1].set_ylabel('Cost')",
    "axes[1].set_title('Predictor-corrector cost breakdown'); axes[1].legend()",
    "save_fig('09a_guidance')",
    "plt.show()",
))

cells.append(code(
    "# Distribution of chosen bank magnitudes over all guidance updates",
    "if len(g):",
    "    counts = g['guidance_chosen_sigma_mag_deg'].value_counts().sort_index()",
    "    fig, ax = plt.subplots(figsize=(8, 4))",
    "    counts.plot(kind='bar', ax=ax, color='C0')",
    "    ax.set_xlabel('Chosen bank magnitude deg'); ax.set_ylabel('Count')",
    "    ax.set_title('Distribution of chosen predictor-corrector candidates')",
    "    save_fig('09b_candidate_distribution')",
    "    plt.show()",
))

# ---------------------------------------------------------------------------
# 10. RCS firing analysis
# ---------------------------------------------------------------------------
cells.append(md(
    "## 10. RCS firing analysis",
    "",
    "Shows the full chain: commanded bank -> tracking error -> torque command -> RCS firing decision.",
    "The thruster raster plot makes individual firings visible."
))

cells.append(code(
    "# Bank tracking error over time",
    "df['sigma_err_deg'] = np.degrees(df['sigma_cmd_rad'] - df['sigma_actual_rad'])",
    "fig, ax = plt.subplots(figsize=(11, 4))",
    "ax.plot(df['t_s'], df['sigma_err_deg'], color='C3', lw=1, label='sigma_cmd - sigma_actual')",
    "ax.axhline(0, color='k', lw=0.6)",
    "ax.set_xlabel('Time s'); ax.set_ylabel('Bank tracking error deg')",
    "ax.set_title('Bank tracking error')",
    "ax.legend()",
    "save_fig('10a_bank_error')",
    "plt.show()",
))

cells.append(code(
    "# Roll rate and roll acceleration",
    "fig, axes = plt.subplots(1, 2, figsize=(14, 4))",
    "axes[0].plot(df['t_s'], np.degrees(df['roll_rate_rad_s']), color='C0')",
    "axes[0].set_xlabel('Time s'); axes[0].set_ylabel('Roll rate deg/s')",
    "axes[0].set_title('Roll rate')",
    "axes[1].plot(df['t_s'], np.degrees(df['roll_accel_rad_s2']), color='C1')",
    "axes[1].set_xlabel('Time s'); axes[1].set_ylabel('Roll accel deg/s^2')",
    "axes[1].set_title('Roll acceleration')",
    "save_fig('10b_roll_rate_accel')",
    "plt.show()",
))

cells.append(code(
    "# Commanded roll torque vs realized RCS torque, with capacity envelope",
    "fig, ax = plt.subplots(figsize=(12, 4))",
    "ax.plot(df['t_s'], df['tau_roll_cmd_Nm'], color='C0', lw=1.2, label='Commanded torque')",
    "ax.plot(df['t_s'], df['tau_roll_realized_Nm'], color='C1', lw=1.0, alpha=0.8, label='Realized RCS torque (Mz)')",
    "ax.plot(df['t_s'],  df['tau_roll_capacity_Nm'], color='C2', ls='--', lw=0.8, label='+ capacity')",
    "ax.plot(df['t_s'], -df['tau_roll_capacity_Nm'], color='C2', ls='--', lw=0.8, label='- capacity')",
    "ax.set_xlabel('Time s'); ax.set_ylabel('Torque Nm')",
    "ax.set_title('Roll torque: commanded, realized, capacity envelope')",
    "ax.legend(ncol=2)",
    "save_fig('10c_torque')",
    "plt.show()",
))

cells.append(code(
    "# Requested duty cycle and which steps actually produced a firing",
    "fig, axes = plt.subplots(2, 1, figsize=(12, 6), sharex=True)",
    "axes[0].plot(df['t_s'], df['requested_duty'], color='C0', lw=1, label='Requested duty')",
    "axes[0].set_ylabel('Duty (0-1)'); axes[0].set_title('Requested RCS duty cycle')",
    "axes[0].set_ylim(-0.05, 1.05)",
    "fired_idx = df[df['fired_this_step']==1]",
    "axes[1].scatter(fired_idx['t_s'], np.ones(len(fired_idx)), s=8, color='C3',",
    "                label=f'fired_this_step (n={len(fired_idx)})')",
    "axes[1].set_xlabel('Time s'); axes[1].set_ylabel('Fired')",
    "axes[1].set_yticks([0, 1]); axes[1].set_ylim(-0.2, 1.2)",
    "axes[1].legend()",
    "save_fig('10d_duty_vs_fired')",
    "plt.show()",
))

cells.append(code(
    "# Thruster firing raster -- one row per thruster, dots where it fired",
    "if len(thruster_fires_df):",
    "    thruster_names = sorted(thruster_fires_df['thruster'].unique())",
    "    y_index = {name: i for i, name in enumerate(thruster_names)}",
    "    thruster_fires_df['y'] = thruster_fires_df['thruster'].map(y_index)",
    "    pos_names = set(rcs_system.roll_pos_names); neg_names = set(rcs_system.roll_neg_names)",
    "    colors = ['C0' if n in pos_names else ('C3' if n in neg_names else '0.5') for n in thruster_names]",
    "    fig, ax = plt.subplots(figsize=(13, max(3, 0.3*len(thruster_names))))",
    "    for name, c in zip(thruster_names, colors):",
    "        sub = thruster_fires_df[thruster_fires_df['thruster']==name]",
    "        ax.scatter(sub['t_s'], np.full(len(sub), y_index[name]), s=6, color=c)",
    "    ax.set_yticks(list(y_index.values()))",
    "    ax.set_yticklabels(thruster_names)",
    "    ax.set_xlabel('Time s'); ax.set_title('RCS thruster firing raster (blue = +roll pod, red = -roll pod)')",
    "    legend_handles = [Patch(color='C0', label='+roll pod'), Patch(color='C3', label='-roll pod'),",
    "                      Patch(color='0.5', label='other')]",
    "    ax.legend(handles=legend_handles, loc='upper right')",
    "    save_fig('10e_thruster_raster')",
    "    plt.show()",
    "else:",
    "    print('No thruster firings recorded.')",
))

cells.append(code(
    "# Rolling firing frequency (Hz) -- moving average over a 5 s window",
    "win = max(1, int(round(5.0 / dt_s)))",
    "df['fire_rate_hz'] = df['fired_this_step'].rolling(win, min_periods=1).mean() / dt_s",
    "fig, ax = plt.subplots(figsize=(11, 4))",
    "ax.plot(df['t_s'], df['fire_rate_hz'], color='C3', lw=1.2)",
    "ax.set_xlabel('Time s'); ax.set_ylabel('Firing rate Hz (5 s window)')",
    "ax.set_title('Rolling RCS firing frequency')",
    "save_fig('10f_firing_rate')",
    "plt.show()",
))

cells.append(code(
    "# Backlog (pending pulse time) accumulated on each pod",
    "fig, ax = plt.subplots(figsize=(12, 4))",
    "ax.plot(df['t_s'], df['roll_pos_backlog_s'], color='C0', label='+roll pod backlog s')",
    "ax.plot(df['t_s'], df['roll_neg_backlog_s'], color='C3', label='-roll pod backlog s')",
    "ax.set_xlabel('Time s'); ax.set_ylabel('Backlog s')",
    "ax.set_title('RCS pulse backlog by pod')",
    "ax.legend()",
    "save_fig('10g_backlog')",
    "plt.show()",
))

# ---------------------------------------------------------------------------
# 11. Final summary
# ---------------------------------------------------------------------------
cells.append(md("## 11. Final landing summary"))

cells.append(code(
    "R_earth = float(constants.RADIUS_EARTH)",
    "dphi = float(df['phi_rad'].iloc[-1] - target_phi_rad)",
    "dlam = float(df['lam_rad'].iloc[-1] - target_lam_rad)",
    "north_err = R_earth * dphi",
    "east_err = R_earth * dlam * math.cos(target_phi_rad)",
    "ground_err = math.sqrt(north_err**2 + east_err**2)",
    "",
    "sin_dphi2 = math.sin(dphi/2.0); sin_dlam2 = math.sin(dlam/2.0)",
    "a = sin_dphi2**2 + math.cos(float(df['phi_rad'].iloc[-1]))*math.cos(target_phi_rad)*sin_dlam2**2",
    "a = max(0.0, min(1.0, a))",
    "gc_err = R_earth * 2.0 * math.asin(math.sqrt(a))",
    "",
    "landing_summary = {",
    "    'termination_reason': termination_reason,",
    "    'final_t_s': float(df['t_s'].iloc[-1]),",
    "    'final_alt_km': float(df['alt_m'].iloc[-1]/1000.0),",
    "    'final_V_mps': float(df['V_mps'].iloc[-1]),",
    "    'final_gamma_deg': float(math.degrees(df['gamma_rad'].iloc[-1])),",
    "    'final_chi_deg': float(math.degrees(df['chi_rad'].iloc[-1])),",
    "    'final_phi_deg': float(math.degrees(df['phi_rad'].iloc[-1])),",
    "    'final_lam_deg': float(math.degrees(df['lam_rad'].iloc[-1])),",
    "    'north_error_km': north_err/1000.0,",
    "    'east_error_km': east_err/1000.0,",
    "    'flat_ground_error_km': ground_err/1000.0,",
    "    'great_circle_error_km': gc_err/1000.0,",
    "    'rcs_total_fires': int(len(thruster_fires_df)),",
    "    'interval_recenters': int(df['interval_step_recentered'].sum()),",
    "    'interval_splits': int(df['interval_step_split'].sum()),",
    "}",
    "with open(OUTPUT_DIR / 'landing_summary.json', 'w') as f:",
    "    json.dump(landing_summary, f, indent=2)",
    "pd.Series(landing_summary).to_frame('value')",
))

# ---------------------------------------------------------------------------
# Build and save
# ---------------------------------------------------------------------------
nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {
            "name": "python",
            "version": "3.13",
        },
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

with open(NB_PATH, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1)

print(f"Wrote {NB_PATH} with {len(cells)} cells")
